NoMethodError: undefined method `x'
rspec -I. spec/punto_spec.rb
.F

Failures:

  1) Punto Inicialización de un punto Se cuenta con métodos getters para las coordenadas x e y
     Failure/Error: expect(Punto.new(0,0).x).to eq(0)

     NoMethodError:
       undefined method `x' for #<Punto:0x0000562dccfca918 @x=0, @y=0>
     # ./spec/punto_spec.rb:9:in `block (3 levels) in <top (required)>'

Finished in 0.00633 seconds (files took 0.14975 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/punto_spec.rb:8 # Punto Inicialización de un punto Se cuenta con métodos getters para las coordenadas x e y